### ISSUE TITLE
Moving NetCDF to JuliaGEO (and to julia 0.4)

### ISSUE THREAD

**Issue by meggart** [meggart/NetCDF.jl#1]
Hi all, 

as I mentioned earlier, I have done a big rewrite of the NetCDF package. It was mainly cleaning up code so that it is hopefully easier to maintain, but there are also some new features, mainly that `NcVar` now inherits from AbstractArray, so that the following is possible:

```
v=NetCDF.open("myfile.nc","Tair") 
x=v[1:10,:,20:100] 
```

instead of the old `start` and `count` syntax, which is of course still supported. 
I think since julia 0.4 is going to be released soon I would like to ask interested people to test if everything is still working as expected and report any bugs if they appear.

**Comment by zhujinxuan** [comment]
It is a little strange that, when using Pkg.add("NetCDF") in Julia of version 0.5, it is still the NetCDF in the old git place.  I am not sure whether it is an expected behavior.

Thank you.

```
~/.julia/v0.5/NetCDF  ->git remote show origin
* remote origin
  Fetch URL: git://github.com/meggart/NetCDF.jl.git
  Push  URL: git@github.com:meggart/NetCDF.jl.git
  HEAD branch: master
  Remote branches:
    c-changes tracked
    major     tracked
    master    tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (local out of date)
```

**Comment by lstagner** [comment]
Yes. Once everything is working on Julia 0.4 METADATA.jl needs to be updated.

**Comment by visr** [comment]
This repository is forked from meggart/NetCDF.jl to JuliaGeo. I believe that in the original repo under settings, 'transfer ownership' should be chosen to properly move it over. And also update METADATA.jl indeed.

**Comment by meggart** [comment]
Ok, I didn't know about the transfer option, I will check this out. The only thing that is not working yet which was on my list was to make precompilation work. I am very short of time, so maybe it would be worth tagging a new version now, so that the deprecation warnings disappear.

**Comment by meggart** [comment]
Looks like I completely messed up things. I can't transfer the project when there is already a fork, so it looks like I have to delete the fork and transfer afterwards... 

Will make sure that both are synchronized before I do.

**Comment by meggart** [comment]
Before I do this @visr what is the downside of having this repo as a fork? I thought it would be safer this way to not break any existing links...

**Comment by visr** [comment]
Have to say I don't know much about this. I believe GitHub will take care of redirects automatically. And  because it says right under the title on this page "forked from meggart/NetCDF.jl", it may be confusing, people may not think the package is maintained here.

**Comment by meggart** [comment]
Ok, I think I will contact Github to delete the fork dependency as decribed here http://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository it seems to be the simplest way...

**Comment by meggart** [comment]
So the JuliaGeo NetCDF is root now.

**Comment by zhujinxuan** [comment]
I guess that this respotory is still not registered in METADATA.jl

https://github.com/JuliaLang/METADATA.jl/blob/9a1421efe39e0d703ba604b8df9ab86be535de2c/NetCDF/url

**Comment by meggart** [comment]
done

https://github.com/JuliaLang/METADATA.jl/pull/3990#event-459311427
