### ISSUE TITLE
FreeBSD precompilation fails

### ISSUE THREAD

**Issue by milankl** [meggart/NetCDF.jl#101]
I have a [package](https://github.com/milankl/Juls.jl), which [fails the cirrus-ci tests](https://github.com/milankl/Juls.jl/runs/275264643) on FreeBSD with Julia 1.0,1.2 as well as nightly due to its dependencies on NetCDF.jl, whereas Linux, osx, win pass (with Travis & appveyor). 

```
 [1] error(::String) at ./error.jl:33
 [2] top-level scope at /.julia/packages/NetCDF/wnKH9/src/netcdf_c.jl:7
 [3] include at ./boot.jl:328 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1094
 [5] include at ./Base.jl:31 [inlined]
 [6] include(::String) at /.julia/packages/NetCDF/wnKH9/src/NetCDF.jl:3
 [7] top-level scope at /.julia/packages/NetCDF/wnKH9/src/NetCDF.jl:8
...
in expression starting at /.julia/packages/NetCDF/wnKH9/src/netcdf_c.jl:4
in expression starting at /.julia/packages/NetCDF/wnKH9/src/NetCDF.jl:8
```

**Comment by visr** [comment]
Cool package!

So the error is coming from BinDeps, failing [here](https://github.com/JuliaGeo/NetCDF.jl/blob/v0.8.0/src/netcdf_c.jl#L7). 

We can try to get this to work by adding an appropriate entry for FreeBSD to [build.jl](https://github.com/JuliaGeo/NetCDF.jl/blob/080cb8b147dc2d56deddf917a1de47a45b93f136/deps/build.jl) perhaps? Although I'm not sure what this entry should be.

Is this only for CI, or do you intend to run on FreeBSD directly?

Slightly longer term we should strive to get away from BinDeps and build NetCDF Artifacts, using BinaryBuilder + the new Pkg artifacts system that is added in julia 1.3.

**Comment by milankl** [comment]
I don't use FreeBSD directly, but I thought you may want that NetCDF.jl runs on it.

**Comment by visr** [comment]
Yeah indeed, thanks for creating the issue! I think if someone using FreeBSD could help out here that would be the quickest. Otherwise I'd have to debug using CI and no FreeBSD experience.

**Comment by milankl** [comment]
@giordano do you know whether this is a common error with FreeBSD & BinDeps?

**Comment by giordano** [comment]
What is common is that FreeBSD is not much tested, hence errors are not frequently caught :sweat_smile:  But often errors in FreeBSD are indication of something truly wrong which by chance doesn't trigger an error on other platforms

**Comment by giordano** [comment]
Oh, right, sorry I didn't follow very well the thread (I was more thinking about BinaryProvider rather than BinDeps).

@visr Maybe it would be better to build NetCDF with BinaryBuilder?  Have you ever tried that?

**Comment by visr** [comment]
Nope I haven't tried yet, but I'd love to, once I get BB working on Windows.

Now that there is a HDF5Builder it should be easier.

**Comment by giordano** [comment]
Oh, it depends on HDF5?  That's unfortunate, in Yggdrasil we have HDF5 only for few platforms (the most common ones): https://github.com/JuliaPackaging/Yggdrasil/blob/20a84ddd0a0128ee10a0797636544243e0aa9b8c/H/HDF5/build_tarballs.jl#L78-L84 :persevere: 

@milankl I think that for the time being you should give up testing your package for FreeBSD, there is currently no easy way to get all your dependencies on that platform.

**Comment by visr** [comment]
Yep it depends on libhdf5, libcurl and zlib. Too bad a FreeBSD HDF5 build is not yet available. We can keep this issue open for visibility though.

**Comment by visr** [comment]
FreeBSD builds are now available in the latest NetCDF_jll build. If you can, please try them out. I'll close the issue, but feel free to re-open if it doesn't work.

Details in https://github.com/Alexander-Barth/NCDatasets.jl/issues/116#issuecomment-1573850114
