### ISSUE TITLE
ncinfo used to be a struct, now it is Nothing

### ISSUE THREAD

**Issue by physicalbitcoin** [meggart/NetCDF.jl#109]
In latest NetCDF package in Julia 1.2 the return type of the ncinfo() function has changed. Previously it was a struct with fields for global attributes, variable names, etc. Now it is of type Nothing.

Was this change intended?

Do you know the revision number where this was changed?

**Comment by visr** [comment]
Hmm I cannot see anything about `ncinfo` returning a struct previously. The function only opens a NetCDF file, and calls `Base.show` on it. `Base.show` is supposed to return `nothing`, and as far as I can tell that's what it always did.

Do you still see the information being printed out though?

**Comment by jarlela** [comment]
In version 0.8.0 and earlier `ncinfo` returned an `NcFile` object.

**Comment by visr** [comment]
Ah I see. So it was changed in #95, which was released in 0.8.1. That should have been a breaking release then. Sorry about that.

Now that it changed, I guess we may as well keep it? It doesn't make much sense to me to return a `NcFile` here, though I understand people have come to rely on it.

**Comment by physicalbitcoin** [comment]
Oh, thx. I did not realize it was an NcFile. I experimented, and I see I can get the same result from NetCDF.open. It is handy to have the structure to parse out variable lengths and such:

nx=Int(nc.:vars[var].:dim[1].:dimlen)

-All the best

**Comment by visr** [comment]
Ok, thanks for letting us know. I included a warning about this in the release notes at https://github.com/JuliaGeo/NetCDF.jl/releases/tag/v0.8.1.
