### ISSUE TITLE
ncinfo(filename) showing no data

### ISSUE THREAD

**Issue by errearanhas** [meggart/NetCDF.jl#124]
Hello!
Trying to read a NetCDF4 file, using _NetCDF.jl_, and although I can read it in Python with netCDF4 package (so I conclude the file is ok), in Julia I can’t even get general information with _ncinfo(filename)_, as my print shows. Any guess on the problem?

(any file from [here](https://portal.nersc.gov/project/ClimateNet/climatenet_data/) can be used for testing)

my environment:
- macOS Catalina (10.15.5)
- Julia v1.4.2
- Atom v0.12.15
- Juno v0.8.2
- NetCDF v0.10.2

<img width="925" alt="Screen Shot 2020-07-03 at 17 04 14" src="https://user-images.githubusercontent.com/12888985/86495354-67d06c80-bd4f-11ea-82aa-4aa0540793d3.png">

**Comment by visr** [comment]
Hi! Welcome, and thanks for the clear report.

I downloaded one of the files and confirmed your finding.

Then I had a look a the structure of the data.
```
$ ncdump -k data-1996-06-09-01-1.nc
netCDF-4

$ ncdump -h data-1996-06-09-01-1.nc
netcdf data-1996-06-09-01-1 {

group: data {
  dimensions:
        lat = 768 ;
        lon = 1152 ;
  variables:
        float TMQ(lat, lon) ;
                TMQ:description = "total (vertically integrated) precipitable water" ;
                TMQ:units = " kg/m^2" ;
⋮
```

Compared to other files that do work, I noticed this has everything stored in a group called data. In the issues I found #93, so it seems to not be supported right now. Easiest way to continue for you is probably to use the https://github.com/Alexander-Barth/NCDatasets.jl package. I verified it works there:

```julia
julia> using NCDatasets

julia> ds = NCDataset("data-1996-06-09-01-1.nc")
NCDataset: data-1996-06-09-01-1.nc
Group: /

Groups
  NCDataset: data-1996-06-09-01-1.nc
  Group: data

  Dimensions
     lat = 768
     lon = 1152

  Variables
    TMQ     (1152 × 768)
      Datatype:    Float32
      Dimensions:  lon × lat
      Attributes:
       description          = total (vertically integrated) precipitable water
       units                =  kg/m^2
⋮
julia> ds.group["data"]["TMQ"]
TMQ (1152 × 768)
  Datatype:    Float32
  Dimensions:  lon × lat
  Attributes:
   description          = total (vertically integrated) precipitable water
   units                =  kg/m^2
```

See also https://alexander-barth.github.io/NCDatasets.jl/latest/dataset/#Groups-1

**Comment by errearanhas** [comment]
Great, @visr.
Thank you very much for taking some time for helping.
Closing the issue.
