### ISSUE TITLE
Miniconda has acquired new site.

### ISSUE THREAD

**Issue by xanfus** [meggart/NetCDF.jl#128]
```
(@v1.5) pkg> build NetCDF
   Building Conda ─→ `C:\Users\<user>\.julia\packages\Conda\3rPhK\deps\build.log`
   Building NetCDF → `C:\Users\<user>\.julia\packages\NetCDF\0sRUL\deps\build.log`
┌ Error: Error building `NetCDF`:
│ [ Info: Downloading miniconda installer ...
│ ┌ Error: Download failed: curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - ������� ������ �� ������ ���������� �������� ������ ��� �����������.
│ └ @ Base download.jl:43
│ ERROR: LoadError: failed process: Process(`'C:\Windows\System32\curl.exe' -s -S -g -L -f -o 'C:\Users\<user>\.julia\conda\3\installer.exe' https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe`, ProcessExited(35)) [35]
│ 
│ Stacktrace:
│  [1] pipeline_error at .\process.jl:525 [inlined]
│  [2] download_curl(::String, ::String, ::String) at .\download.jl:44
│  [3] download at .\download.jl:62 [inlined]
│  [4] _install_conda(::Symbol, ::Bool) at C:\Users\<user>\.julia\packages\Conda\3rPhK\src\Conda.jl:164
│  [5] _install_conda at C:\Users\<user>\.julia\packages\Conda\3rPhK\src\Conda.jl:155 [inlined]
│  [6] parseconda(::Cmd, ::Symbol) at C:\Users\<user>\.julia\packages\Conda\3rPhK\src\Conda.jl:120
│  [7] search(::String, ::Symbol) at C:\Users\<user>\.julia\packages\Conda\3rPhK\src\Conda.jl:261
│  [8] exists(::String, ::Symbol) at C:\Users\<user>\.julia\packages\Conda\3rPhK\src\Conda.jl:285
│  [9] package_available at C:\Users\<user>\.julia\packages\CondaBinDeps\rN3r7\src\bindeps_conda.jl:19 [inlined]
│  [10] can_provide(::CondaBinDeps.EnvManager{Symbol("C:\\Users\\<user>\\.julia\\conda\\3")}, ::Dict{Symbol,Any}, ::BinDeps.LibraryDependency) at C:\Users\<user>\.julia\packages\BinDeps\QvmEl\src\dependencies.jl:799
│  [11] _find_library(::BinDeps.LibraryDependency; provider::Type{T} where T) at C:\Users\<user>\.julia\packages\BinDeps\QvmEl\src\dependencies.jl:656
│  [12] _find_library at C:\Users\<user>\.julia\packages\BinDeps\QvmEl\src\dependencies.jl:650 [inlined]
│  [13] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at C:\Users\<user>\.julia\packages\BinDeps\QvmEl\src\dependencies.jl:929 (repeats 2 times)
│  [14] top-level scope at C:\Users\<user>\.julia\packages\BinDeps\QvmEl\src\dependencies.jl:984
│  [15] include(::String) at .\client.jl:457
│  [16] top-level scope at none:5
│ in expression starting at C:\Users\<user>\.julia\packages\NetCDF\0sRUL\deps\build.jl:15
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Operations.jl:949
```
Filesystem isn't found at  https://**repo.continuum.io**/miniconda/Miniconda3-latest-Windows-x86_64.exe
Instead it is at https://**repo.anaconda.com**/miniconda/Miniconda3-latest-Windows-x86_64.exe

**Comment by ali-ramadhan** [comment]
Ah that's unfortunate and will probably break a lot of things but I think it has nothing to do with NetCDF.jl and must be fixed upstream in https://github.com/JuliaPy/Conda.jl

**Comment by xanfus** [comment]
Is the issue considered closed, then?

**Comment by ali-ramadhan** [comment]
Ah sorry @xanfus I didn't mean to come off as an authority. I'm not a contributor/maintainer of NetCDF.jl. Just saw your issue and thought I should mention Conda.jl.

I'll let the maintainers of NetCDF.jl decide whether to keep this issue open (until `build NetCDF` works again) but might be a good idea to also open an issue on Conda.jl

**Comment by xanfus** [comment]
I had opened an issue at Conda.jl. There are lines at Conda package in file Conda.jl:
```
"Get the miniconda installer URL."
function _installer_url()
    res = "https://repo.continuum.io/miniconda/Miniconda$(MINICONDA_VERSION)-latest-"
    if Sys.isapple()
```
I just had to go up the stacktrace. I will edit the line and proceed.

**Comment by visr** [comment]
> Filesystem isn't found at https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe
Instead it is at https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe

Both links are working fine for me, it seems the needed redirects are in place. Opening https://repo.continuum.io/miniconda/ takes you to https://repo.anaconda.com/miniconda/. Still would be good to update the URL in Conda.jl though.

The error you get seems to be different, since it says `Download failed: curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012)`. Not sure what causes it, but here are more people with the same issue: https://github.com/jeroen/curl/issues/127. Are you on an older Windows version? You may need to apply the TLS easy fix: https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi#easy.

**Comment by xanfus** [comment]
I'm on Win 10 20H2 19042.610. Thanks for directions.

**Comment by visr** [comment]
Closing, because since #123 we don't use the Conda build anymore.
