### ISSUE TITLE
NetCDF v0.11 only for Julia 1.3?

### ISSUE THREAD

**Issue by milankl** [meggart/NetCDF.jl#130]
https://github.com/JuliaGeo/NetCDF.jl/blob/b1139d860fefe200c54fbb5c657b7b309a82ce31/Project.toml#L17

Is that on purpose?

**Comment by milankl** [comment]
Sorry, my fault, I misread some compat specifiers between NetCDF and ShallowWaters ;)

**Comment by visr** [comment]
Yes, it's because we switched to getting our binaries from Artifacts, which are julia 1.3+

**Comment by milankl** [comment]
Getting confused here, I currently can't install the newest version on 1.5.2
```
(@v1.5) pkg> add NetCDF
  Resolving package versions...
Updating `~/.julia/environments/v1.5/Project.toml`
  [30363a11] + NetCDF v0.10.3
No Changes to `~/.julia/environments/v1.5/Manifest.toml`
```

**Comment by milankl** [comment]
@gaelforget that's because of [IndividualDisplacements.jl](https://github.com/JuliaClimate/IndividualDisplacements.jl) which should probably also be update to `NetCDF = "^0"` or similar. As far as I understand 0.11 is not a breaking change from 0.10?

**Comment by milankl** [comment]
Sorry, my bad, you already fixed that.
