### ISSUE TITLE
Julia 1.6.0 compatibility

### ISSUE THREAD

**Issue by Yujie-W** [meggart/NetCDF.jl#137]
Julia Registrator added a CI check for Julia 1.6, and NetCDF is preventing the importing of Packages that depend on it. Can you check what is the issue with this?
The error message is
```
[ Info: Successfully `Pkg.add`ed package
[ Info: Attempting to `import` package
ERROR: LoadError: InitError: could not load library "/tmp/jl_473A8V/artifacts/877149aedda703fde4a848bffd955df8934ca876/lib/libnetcdf.so"
libmbedtls.so.12: cannot open shared object file: No such file or directory
```

**Comment by visr** [comment]
Ah yeah I just had the same problem. That registry check should not be on the beta release of julia. It's not mandatory to pass. I asked on Slack in #pkg-registration and it was directly merged.

That said, we are aware of the issue, and working to resolve it in https://github.com/JuliaPackaging/Yggdrasil/pull/2402.

**Comment by visr** [comment]
The new build is registered, but we still need to allow it in Project.toml and do a new release, https://github.com/JuliaPackaging/Yggdrasil/pull/2402#issuecomment-767960298.

**Comment by meggart** [comment]
Can we close this?

**Comment by Yujie-W** [comment]
Thanks.
