### ISSUE TITLE
Reading netCDF with groups

### ISSUE THREAD

**Issue by ezaron** [meggart/NetCDF.jl#145]
Hello,
Is the netCDF.jl package capable of reading netCDF files containing groups of variables?
I can see the groups, variables, and data using ncdump from the command-line, but everything I try using ncread from julia cannot find the variables.
-Ed

**Comment by visr** [comment]
I believe this comment still holds: https://github.com/JuliaGeo/NetCDF.jl/issues/93#issuecomment-519662914
Though you could also have a look at https://github.com/Alexander-Barth/NCDatasets.jl, it looks like groups are supported.
