### ISSUE TITLE
Out-of-date NetCDF_jjl and HDF5_jjl for M1 Mac

### ISSUE THREAD

**Issue by samhatfield** [meggart/NetCDF.jl#157]
On my M1 Macbook Pro I install NetCDF.jl with
```
pkg> add NetCDF
...
  [0234f1f7] + HDF5_jll v1.12.0+1
  [7243133f] + NetCDF_jll v400.702.400+0
...
```

However we know that we need NetCDF_jll v400.702.402+0 and HDF5_jll v1.12.1+0 (see https://github.com/Alexander-Barth/NCDatasets.jl/issues/150) on M1 CPUs. It therefore doesn't work:
```
julia> using NetCDF

julia> ncinfo("test.nc")
ERROR: UndefVarError: libnetcdf not defined
Stacktrace:
 [1] nc_open
   @ ~/.julia/packages/NetCDF/2wjHP/src/netcdf_c.jl:55 [inlined]
 [2] nc_open(fname::String, omode::UInt16)
   @ NetCDF ~/.julia/packages/NetCDF/2wjHP/src/netcdf_helpers.jl:103
 [3] open(fil::String; mode::UInt16, readdimvar::Bool, add_finalizer::Bool)
   @ NetCDF ~/.julia/packages/NetCDF/2wjHP/src/NetCDF.jl:913
 [4] open(f::typeof(show), args::String; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ NetCDF ~/.julia/packages/NetCDF/2wjHP/src/NetCDF.jl:999
 [5] open
   @ ~/.julia/packages/NetCDF/2wjHP/src/NetCDF.jl:999 [inlined]
 [6] ncinfo(fil::String)
   @ NetCDF ~/.julia/packages/NetCDF/2wjHP/src/NetCDF.jl:1101
 [7] top-level scope
   @ REPL[3]:1
```

I can fix this with
```
pkg> add NetCDF_jll@v400.702.402
```
which also brings in HDF5_jll v1.12.1+0. So maybe this is simply a case of updating Project.toml?

**Comment by visr** [comment]
That is indeed the right fix for you right now to get a working build.

The new build adds Apple M1 support, but is broken on Windows. That is really a pity, and we hope it can be resolved soon. Since Julia's Pkg cannot set package compatibilities per platform, we have to choose for either Windows or M1 users in our current compatability. Since Windows worked before, and probably has more users, we decided to go with that for now.

See also https://github.com/Alexander-Barth/NCDatasets.jl/issues/164

**Comment by samhatfield** [comment]
That's fair enough. I guess this will be solved in the future, but perhaps best to leave this issue open until then, and so others on M1s know how to proceed until then?

**Comment by visr** [comment]
Yeah I think that's a good idea. You mention having to do

```
pkg> add NetCDF_jll@v400.702.402
```

I'm assuming what that does is it will install NetCDF v0.11.4, which is the last release before #155.

**Comment by samhatfield** [comment]
Oh you're right, I didn't notice that. So a simpler solution is
```
pkg> add NetCDF@0.11.4
```

**Comment by truedichotomy** [comment]
The latest master branch of NCDatasets.jl uses NetCDF_jll v400.802.103 and HDF5_jll v1.12.1, which is currently incompatible with NetCDF.jl v0.11.6.
