### ISSUE TITLE
Variable's scale_factor and add_offset are not taken into account during reading

### ISSUE THREAD

**Issue by laclouis5** [meggart/NetCDF.jl#165]
For instance a variable with storage type `SHORT` and with defined `scale_factor`and `add_offset`is not interpreted as FLOAT during reading, which is not the expected behavior. As a comparison, the Python package `NetCDF4` does the right conversion during reading.

**Comment by visr** [comment]
You're right, they are not taken into account. I'll close this as a duplicate of #39. There is also some discussion here: https://github.com/JuliaGeo/NetCDF.jl/issues/131#issuecomment-739063179. I think the options are right now to either do it manually using this package, or use https://github.com/Alexander-Barth/NCDatasets.jl.
