### ISSUE TITLE
Ncread throws: invalid array dimensions while reading a variable.

### ISSUE THREAD

**Issue by aramirezreyes** [meggart/NetCDF.jl#19]
Hi! using v 0.4.2

I'm trying to read, from a NetCDF file, variable, in fact several of them with no success:
Example: This ZNU variable has the size 24*27 and i can't read it with.

```
julia> ncread(Arch,"ZNU",start=[1,1],count=[-1,1])
ERROR: invalid Array dimensions
 in call at essentials.jl:201
 in ncread at /home/argel/.julia/v0.4/NetCDF/src/NetCDF.jl:545
```

If i preallocate the destination array 
`Znu = zeros(27)`
 I can succesfully read it:

```
ncread!(Arch,"ZNU", Znu,start=[1,1],count=[-1,1])
27-element Array{Float64,1}
```

The description of this variable, according to ncinfo is:

```
ZNU                  units                                                          
ZNU                  stagger                                                        
ZNU                  FieldType            104                                       
ZNU                  MemoryOrder          Z                                         
ZNU                  description          eta values on half (mass) levels  
```

Is this a bug or doing something wrong?

**Comment by meggart** [comment]
I think this is a bug. I am very busy right now, I hope I can look into this over the weekend.

**Comment by argelouski** [comment]
Thanks man!

**Comment by meggart** [comment]
I can't reproduce the error yet, this is what I tried:
````julia
    using NetCDF
    Arch="readtest.nc"
    #Create file with your dimensions
    nccreate("readtest.nc","ZNU","d1",24,"d2",27,t=Float64)
    #Write some data
    ncwrite(rand(24,27),"readtest.nc","ZNU")
    #Read data
    ncread(Arch,"ZNU",start=[1,1],count=[-1,1])
````

This works for me without throwing an error. Is there a way to reproduce the error?

**Comment by argelouski** [comment]
Hmmm, weird stuff...
I just renstalled NetCDF package since i thought it could be something wrong, but still.
```
julia> using NetCDF
julia> Arch="readtest.nc"
"readtest.nc"
julia> #Create file with your dimensions
          nccreate("readtest.nc","ZNU","d1",24,"d2",27,t=Float64)
julia> #Write some data
          ncwrite(rand(24,27),"readtest.nc","ZNU")
julia> #Read data
          ncread(Arch,"ZNU",start=[1,1],count=[-1,1])
ERROR: invalid Array dimensions
 in call at essentials.jl:201
 in ncread at /home/argel/.julia/v0.4/NetCDF/src/NetCDF.jl:545
```

Pkg.status() shows NetCDF version 0.3.0 with julia 0.4.2

Maybe another dependency failing? it jumps when calling essentials.jl, i will try a clean julia installation...

**Comment by evanmason** [comment]
I have the exact same error as @argelouski on a totally clean OS (Mageia 5) and Julia install.

**Comment by argelouski** [comment]
Hi!
Installed yesterday on a clean Debian Stretch installation and the problem
appears too.

How can we help?

2016-02-09 11:34 GMT-06:00 evanmason <notifications@github.com>:

> I have the exact same error as @argelouski <https://github.com/argelouski>
> on a totally clean OS (Mageia 5) and Julia install.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaGeo/NetCDF.jl/issues/19#issuecomment-181973053>.
>



-- 
Argel Ramírez R.

**Comment by meggart** [comment]
Ok, I could reproduce the bug on 0.3.0, on master it seems to work for me. Could you please confirm that the bug is gone after Pkg.checkout("NetCDF"). Then the obvious fix would be to tag a new version on METADATA.

**Comment by evanmason** [comment]
Yes, for me the bug has gone now.  Thanks a lot.

**Comment by argelouski** [comment]
It is gone, thanks!
