### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by christinegz** [meggart/NetCDF.jl#191]
The error message for checking the length of count in readvar appears wrong;

[NetCDF.jl, line 344 ](https://github.com/JuliaGeo/NetCDF.jl/blob/41dcc7c5e906895b55492cf529c8af48d77fd658/src/NetCDF.jl#L344):

```
    length(count) == v.ndim || error("Length of start ($(length(count))) must equal the number of variable dimensions ($(v.ndim))")
```

Please change "Length of start" to "Length of count"

**Comment by visr** [comment]
Thanks for the report! Fix in #192.
