### ISSUE TITLE
Trying to use Conda as a binary provider under Linux and Windows

### ISSUE THREAD

**Issue by meggart** [meggart/NetCDF.jl#2]
It would be cool if we could use Conda.jl (many thanks to @Luthaf) to provide binaries under Windows and Linux without root access. What works so far is 

```
using Conda
Conda.add("libnetcdf")
```

this will install the Conda libnetcdf package and put some netcdf.ddl/so in `.julia//v0.4/Conda/deps/usr/pkgs/libnetcdf-4.3.3.1-1/lib` under Linux or `/v0.4/Conda/deps/usr/pkgs/libnetcdf-4.3.3.1-1/bin` when I am on Windows. 

However Libdl.find_library does not automatically detect the files in these paths. 
@Luthaf could you help/explain how we can make this work?

**Comment by Luthaf** [comment]
>  @Luthaf could you help/explain how we can make this work?

This could be done using the BinDeps provider integrated with Conda.

```julia
# In deps/build.jl
using BinDeps
@BinDeps.setup
netcdf = library_dependency("netcdf", aliases = ["libnetcdf","libnetcdf4"])
using Conda
provides(Conda.Manager, "libnetcdf", netcdf)
```

[HS] This is actually my README example :smile: [/HS]

**Comment by meggart** [comment]
I know this is in the README and I tried it and it produced an error message for me under Windows (should have mentioned that), this is why I tried to install manually. I checked now on my MacBook and it works like a charm. Will try on Windows again this afternoon, maybe it just a stupid error from my side...

**Comment by Luthaf** [comment]
I recently pushed some fixes for Windows installation (Luthaf/Conda.jl#5), so this might have been the origin of your errors.

**Comment by meggart** [comment]
Ok, installation of the conda package works now automatically when calling 

Pkg.build("NetCDF")

Still, in order to make them visible I have to add these lines to NetCDF.jl

    import Conda.PREFIX
    @unix_only push!(Libdl.DL_LOAD_PATH,joinpath(PREFIX, "lib"))
    @windows_only push!(Libdl.DL_LOAD_PATH,joinpath(PREFIX, "pkgs", version(m.packages[1]), "Library", "bin"))

**Comment by Luthaf** [comment]
Have you tried using:
```
using BinDeps
@BinDeps.load_dependencies
```
In your module file (NetCDF.jl)?

**Comment by meggart** [comment]
Ok, this was the missing piece, I thought it was the task of the BinDeps provider to export the paths (like for Homebrew where `using Homebrew` will add the respective DL_LOAD_PATHs)

Thanks for your help and excuse my not reading documentation.

**Comment by Luthaf** [comment]
No problem, it is great you managed to used it!
