### ISSUE TITLE
 NcDim cannot work with an error about `convert'

### ISSUE THREAD

**Issue by zhujinxuan** [meggart/NetCDF.jl#24]
When I run the example code under `julia 0.4.0-dev+3004`, I find that `NcDim` and other commands relate to `NcDim` (`nccreate` for example) do not work.

This is the error I got when running the example code `low.jl`

```
timdim = NcDim("time",tim,timatts)
ERROR: MethodError: `convert` has no method matching convert(::Type{NetCDF.NcDim}, ::ASCIIString, ::Array{Int64,1}, ::Dict{ASCIIString,ASCIIString})
This may have arisen from a call to the constructor NetCDF.NcDim(...), since type constructors fall back to convert methods in julia v0.4.
Closest candidates are:
  convert(::Type{Ptr{UInt8}}, ::Union(UTF8String,ASCIIString))
  convert(::Type{Ptr{Int8}}, ::Union(UTF8String,ASCIIString))
  convert(::Type{ASCIIString}, ::ASCIIString)
  ...

 in call at ./base.jl:36
```

I am not sure whether it is related to something new in the julia 0.40.

Thank you for your time.

**Comment by meggart** [comment]
I installed julia-0.4 and I think I fixed all the issues and deprecation warnings 742f13fcc5f85. At least the tests pass...
You have to checkout master to see the changes: `Pkg.checkout("NetCDF")`

This, will hopefully, be the last commit on this branch, the package is reorganized, in the "major" branch, which will then also be 0.4-compatible, once it is done.

**Comment by zhujinxuan** [comment]
My problem. I just find that it works right after rebooting my computer...
Thank you for your reply.
