### ISSUE TITLE
seg fault trying to modify global attribute

### ISSUE THREAD

**Issue by evanmason** [meggart/NetCDF.jl#26]
Hi, I am trying to modify a global attribute ("loess_span") using:

```ncputatt(filename, "loess_span", Dict("loess_span", loess_span))```

in an existing netcdf file:
```
netcdf my_chl_qggrid_file {
dimensions:
        lon = 301 ;
        lat = 61 ;
        time = UNLIMITED ; // (3104 currently)
variables:
        double lon(lat, lon) ;
                lon:_FillValue = 9999. ;
        double lat(lat, lon) ;
                lat:_FillValue = 9999. ;
// global attributes:
                :loess_span = 0. ;
```
but I get the following seg fault:
```
julia> include("make_chl_loess.jl")

signal (11): Segmentation fault
NC4_put_att at /opt/lib/libnetcdf.so (unknown line)
nc_put_att_float at /opt/lib/libnetcdf.so (unknown line)
_nc_put_att_float_c at /home/emason/.julia/v0.3/NetCDF/src/netcdf_c_wrappers.jl:116
jlcall__nc_put_att_float_c_20661 at  (unknown line)
jl_apply_generic at /opt/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
_nc_put_att at /home/emason/.julia/v0.3/NetCDF/src/netcdf_helpers.jl:102
jlcall__nc_put_att_20659 at  (unknown line)
jl_apply_generic at /opt/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
putatt at /home/emason/.julia/v0.3/NetCDF/src/NetCDF.jl:149
jlcall_putatt_20629 at  (unknown line)
jl_apply_generic at /opt/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
putatt at /home/emason/.julia/v0.3/NetCDF/src/NetCDF.jl:160
jl_apply_generic at /opt/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
ncputatt at /home/emason/.julia/v0.3/NetCDF/src/NetCDF.jl:172
jl_apply_generic at /opt/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
unknown function (ip: 402299928)
unknown function (ip: 402296441)
unknown function (ip: 402363022)
unknown function (ip: 402365696)
jl_load at /opt/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
include at ./boot.jl:245
jl_apply_generic at /opt/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
include_from_node1 at ./loading.jl:128
jl_apply_generic at /opt/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
unknown function (ip: 402299928)
unknown function (ip: 402296441)
unknown function (ip: 402363022)
jl_f_top_eval at /opt/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
eval_user_input at REPL.jl:53
jlcall_eval_user_input_20293 at  (unknown line)
jl_apply_generic at /opt/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
anonymous at task.jl:95
jl_handle_stack_switch at /opt/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
julia_trampoline at /opt/julia/julia/usr/bin/../lib/libjulia.so (unknown line)
unknown function (ip: 4199581)
__libc_start_main at /lib64/libc.so.6 (unknown line)
unknown function (ip: 4199635)
unknown function (ip: 0)
Segmentation fault
```
Does NetCDF.jl allow this operation on global attributes, or is my call to ncputatt wrong?

Thanks

**Comment by meggart** [comment]
Hmm, I haven|t seen this before, in general this should work. What is the type of your attribute and which julia version do you use?

**Comment by evanmason** [comment]
I guess it's a float 64; the nc file where the attribute was first set was created with python.netcdf4 with the line:
```nc.loess_span = 0.```

and in my Julia script I have:
```loess_span = 0.1```
just before the call to ncputatt()

I am using Julia Version 0.3.12-pre+5 Commit 24138e7* (33 days old release-0.3)

**Comment by meggart** [comment]
I think your DIct is not constructed correctly, could you please try the syntax:

    ncputatt(filename, "loess_span", {"loess_span" => loess_span})

and test if it works. There might still be an issue with the package, it should never segfault, but can you try if this works for you?

**Comment by evanmason** [comment]
Perfect, it worked:
```:loess_span = 0.1f ;```

Can you explain why the syntax I used failed?  (I've only been using Julia for about a week.)

One other comment,  in the documentation it says to use ncsync as:
```ncsync( [ filename ] )```

but I found it would not accept the filename: instead I used just:
```
ncsync()
```

Is it necessary to use `ncclose()` when using the high level interface?

Thanks for your help.

**Comment by meggart** [comment]
The Dict constructor you have been using accepts an iterable of keys as the first and an iterable of values as the second argument. So it just created a Dict containing a single pair 
````julia
julia> Dict("loess_span", 0.1)
Dict{Any,Any} with 1 entry:
  'l' => 0.1
````
This is quite unfortunate and the Dict construction syntax is going to be changed in julia v0.4. 

You are right with `ncsync(filename)` I forgot to implement this so far, but ncsync() should do what you want. I will add this to the new version. 

Regarding `ncclose`, if you open your files in write mode, you should definitely close them to make sure the data gets actually written to disk. If you are in read mode and you don't leave millions of files open it should be ok if you don't ncclose, files will be closed when you quit julia.

**Comment by evanmason** [comment]
Ok, great, thanks again for your help.  Evan
