### ISSUE TITLE
using NetCDF (enhancement manual)

### ISSUE THREAD

**Issue by mvhulten** [meggart/NetCDF.jl#26]
For some people (like me) `NetCDF.jl` may be the first package they install. They will get an error because, when following the manual, they didn't actually load the package.

In `README.md` just after (or before) **Quickstart** add the command `using NetCDF`.

Maybe also in `https://github.com/meggart/NetCDF.jl/blob/master/doc/NetCDF.md`.

**Comment by meggart** [comment]
Good idea, thanks. Documentation pull requests are very easy to do, just click the edit button on the Github page, make your modifications and create a pull request. 

Otherwise I could also take care of the changes..

**Comment by mvhulten** [comment]
Thank you for the help, and for merging my commit!
