### ISSUE TITLE
off by one error in nc_get_att?

### ISSUE THREAD

**Issue by kilminster** [meggart/NetCDF.jl#30]
I'm finding the last character of attributes is being cut off, and errors are raised if the attribute is a 0-length string.  I think this is an off by one error, since the following seems to fix it.

line 155 of netcdf_helpers is currently:
`valsa=Array(nctype2jltype[attype],attlen)`
change this to:
`valsa=Array(nctype2jltype[attype],attlen+1)`

**Comment by kilminster** [comment]
The above change is not the right way to fix the problem, as the original issue seems only to affect string valued attributes.  The above change fixes the strings, but messes up numeric valued attributes.  For now, the following change seems to be working:

``` julia
    typ=nctype2jltype[attype]
    if typ==UInt8
        valsa=Array(nctype2jltype[attype],attlen+1)
    else
        valsa=Array(nctype2jltype[attype],attlen)
    end
```

Someone who knows the code better than I do could probably make a less ugly fix.

**Comment by meggart** [comment]
I will look at this next week, thanks for reporting.
