### ISSUE TITLE
readdimvar error after upgrade from 0.

### ISSUE THREAD

**Issue by evanmason** [meggart/NetCDF.jl#31]
nc = NetCDF.open(eddy_file, mode=NC_NOWRITE, readdimvar=true)
xsize = nc.dim["x"].dimlen

LoadError: UndefVarError: _readdimvars not defined
while loading In[10], in expression starting on line 10

 in open at /home/emason/.julia/v0.4/NetCDF/src/NetCDF.jl:528

**Comment by evanmason** [comment]
I now get an error when I set  `readdimvar= true` after upgrading from 0.3 to 0.4:
```
nc = NetCDF.open(eddy_file, mode=NC_NOWRITE, readdimvar=true)
xsize = nc.dim["x"].dimlen

LoadError: UndefVarError: _readdimvars not defined
while loading In[10], in expression starting on line 10

 in open at /home/emason/.julia/v0.4/NetCDF/src/NetCDF.jl:528
```
Thanks again

**Comment by meggart** [comment]
Ok, thanks for testing, is fixed here: https://github.com/JuliaGeo/NetCDF.jl/commit/ecaa6a938bcf256787f793dc01cf08d35c2b32b9
Let me know if there are any further regressions, There was a big package reorganization, I tried to remain backwards-compatible but some things were not covered by tests. 
BTW, the repository was moved to JuliaGeo/NetCDF, so please try to post your issues there. It is a bit unfortunate that google still points to this Repo...

**Comment by evanmason** [comment]
Ok, yes it works now, thanks a lot.  I'll post from now on at JuliaGeo/NetCDF.
