### ISSUE TITLE
Appending values to netCDF4 variable

### ISSUE THREAD

**Issue by Omer80** [meggart/NetCDF.jl#33]
I am transferring my code from Python to Julia, and trying to figure out how to store data into netCDF using this package. If someone can give me a hint it would be great - 
[http://stackoverflow.com/q/35348537/2051572](http://stackoverflow.com/q/35348537/2051572)

**Comment by meggart** [comment]
Hi, 

you will probably have to wait until this https://github.com/JuliaGeo/NetCDF.jl/pull/13 gets merged, I hope to get to it next week and then will reply to your question.

**Comment by Omer80** [comment]
@meggart Is the support for unlimited dimensions works already?
