### ISSUE TITLE
Properly support unlimited dimensions

### ISSUE THREAD

**Issue by meggart** [meggart/NetCDF.jl#4]
It is propably not too much work, I personally just don't use unlimited dimensions so I kind of ignored them so far. This needs to change...

**Comment by rickedanielson** [comment]
The time dimension was traditionally seen to be a good  UNLIMITED candidate for files that were expected grow as an evolution was being followed.  A previous error ("ERROR: LoadError: BoundsError: attempt to access 1-element Array{UTF8String,1}:") was not related, but seemed to be at first.  However, further tests reading a variable whose time dimension is UNLIMITED are passing and perhaps it should be noted (on closing this issue) that unlimited dimensions may not require specific attention...(?)

**Comment by meggart** [comment]
Yes, for reading unlimited dimensions no action is required. Creating files to and writing unlimited dimensions is possible now with #13 . As I just noticed, this is still undocumented #21 , so another todo...
