### ISSUE TITLE
Allow ncclose to accept an NcFile

### ISSUE THREAD

**Issue by squaregoldfish** [meggart/NetCDF.jl#49]
It would be useful to allow `ncclose` to accept an `NcFile` handle as an alternative to a filename. It would be more in line with most other netCDF implementations.

**Comment by visr** [comment]
There is `NetCDF.close(nco::NcFile)`, defined [here](https://github.com/JuliaGeo/NetCDF.jl/blob/fd5cd0481094e6c30d267adafe957006e005128d/src/NetCDF.jl#L526). It's in the docs under the intermediate level API. Does that help?

**Comment by squaregoldfish** [comment]
Ah yes. I missed the second close function. Sorry for the noise.
