### ISSUE TITLE
Can't  install NetCDF Package at Julia 0.4.1 Windows 32-bit or 64-bit

### ISSUE THREAD

**Issue by DuLiangMin** [meggart/NetCDF.jl#6]
in Julia i686-w64-mingw32

```
           _
```

   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.1 (2015-11-08 10:33 UTC)
 _/ |\__'_|_|_|__'_|  |  Official http://julialang.org/ release
|__/                   |  i686-w64-mingw32

I do this's  
Pkg.init()

julia> Pkg.add("NetCDF")
INFO: Installing Formatting v0.1.4
INFO: Installing NetCDF v0.3.0
JULIA_PKGDIR=O:\Julia-0.4.1\bin..\share\julia\site
INFO: Building NetCDF
Fetching package metadata: ....
Solving package specifications: ...............
# All requested packages already installed.
# packages in environment at O:\Julia-0.4.1\share\julia\site\v0.4\Conda\deps\usr

:
# 

libnetcdf                 4.3.3.1                       3
===============================[ ERROR: NetCDF ]================================

LoadError: Provider BinDeps.PackageManager failed to satisfy dependency libnetcd
f
while loading O:\Julia-0.4.1\share\julia\site\v0.4\NetCDF\deps\build.jl, in expr
ession starting on line 12
# 

================================[ BUILD ERRORS ]================================

WARNING: NetCDF had build errors.
- packages with build errors remain installed in O:\Julia-0.4.1\share\julia\sit
  e\v0.4
- build the package(s) and all dependencies with `Pkg.build("NetCDF")`
- build a single package by running its `deps/build.jl` script
# 

INFO: Package database updated
INFO: METADATA is out-of-date —— you may not have the latest version of NetCDF
INFO: Use `Pkg.update()` to get the latest versions of your packages

**Comment by meggart** [comment]
I have also realized this, the netcdf.dll coming with the conda NetCDF seems to be broken. I will look for an alternative. To get the package running anyway, you can install the NetCDF binaries directly from here http://www.unidata.ucar.edu/software/netcdf/docs/winbin.html

I should probably add this to the README.

**Comment by DuLiangMin** [comment]
You can change netcdf.dll to libnetcdf.dll to solve this problem,But I wish use Pkg.add("NetCDF")
auto add libnetcdf.dll to path.

**Comment by meggart** [comment]
I don't think this is a naming problem. I think I fixed the paths and libname. 
Could you please try to call `dlopen("$YOUR_HOME/.julia/v0.4/Conda/deps/usr/pkgs/libnetcdf-4.3.3.1-1/bin/netcdf.dll") after checking the file exists? On my windows test machine it returned an error, which suggests the dll is broken. If it returns a pointer for you, then something about the path seems to be wrong which should be fixable.

**Comment by DuLiangMin** [comment]
JULIA_PKGDIR = O:\Julia-0.4.1\share\julia\site\v0.4\NetCDF
edit JULIA_PKGDIR/v0.4/NetCDF/deps/deps.jl
in line 12
you can find 
@checked_lib libnetcdf "O:\\Julia-0.4.1\\bin\\libnetcdf.DLL"
so change name can run it 
----------------------------------
Pkg Conda I will try it

**Comment by joa-quim** [comment]
One cannot change names of dlls on Windows. They have embedded their original names. The only solution is rebuild with another name.
