### ISSUE TITLE
Slicing of NcVar does not work

### ISSUE THREAD

**Issue by martinclaus** [meggart/NetCDF.jl#72]
Following code throws the error `UndefVarError: start not defined`:

```julia
    ds = NetCDF.open(file_name);
    a = ds[varname][1:2, 1]    # given that length(ds[varname].dim == 2) and size(ds[varname])[1] >= 2
```
However, reading the whole array and then slicing does work (obviously)

```julia
    ds = NetCDF.open(file_name);
    a = ds[varname][:, 1][1:2, :]
```

**Comment by meggart** [comment]
I think this was fixed by #71 but is only available on master right now. Looks like we should tag a new version...

**Comment by Balinus** [comment]
Would be awesome! :+1: 

edit - ClimateTools.jl fails on TravisCI and need to checkout master branch of NetCDF to circumvent this problem (which i do not want to do on travis configuration). Cheers!

**Comment by visr** [comment]
Thanks for the reminder. Tagged a new release, should be merged soon.
https://github.com/JuliaLang/METADATA.jl/pull/18801
