### ISSUE TITLE
ncsync and ncputatt issues after upgrade from 0.3 to 0.4

### ISSUE THREAD

**Issue by evanmason** [meggart/NetCDF.jl#8]
I get one warning and an error following update from 0.3 to 0.4.

The warning:
`WARNING: deprecated syntax "{a=>b, ...}" at /home/emason/julia/make_chl_loess.jl:97.
Use "Dict{Any,Any}(a=>b, ...)" instead.`
relates to this line in my code:
`ncputatt(filename, "loess_span", {"loess_span" => loess_span})`

The error:
`while loading /home/emason/julia/make_chl_loess.jl, in expression starting on line 121
ERROR: LoadError: UndefVarError: _nc_sync_c not defined
 in ncsync at /home/emason/.julia/v0.4/NetCDF/src/NetCDF.jl:369`
relates to this:

```
ncsync()
```

Thanks

**Comment by meggart** [comment]
The warning is about changed Dict syntax in Julia v0.4. The {} will be used for Tuple types soon, so one has to construct Dicts with Dict("loess_span"=>loess_span) now. 

Will look at the ncsync error now.

**Comment by meggart** [comment]
ncsync issue fixed here:
https://github.com/JuliaGeo/NetCDF.jl/commit/84cd7beb07b40d0e5bdf19efb428956029e9ea4c
